#include <stdio.h> // stdio stands for standard input/output. The header file contains the prototypes of the functions belonging to the C standard library which handle I/O.

/*
The function sum is defined as it follows in the code. It accepts two parameters, a and b, which are integer values. Then in the implementation is declared a c variable of type int to which is assigned the value obtained by the expression 'a + b' that is an arithmetic sum between int values.
The value of c is what the function returns. Also notice that the return keyword brings back the control of the execution to the calling function that is in this case the main function.
*/
int sum(int a, int b) {
	int c = a + b;
	return c;
}

/*
The main function is always the starting point of the program.
*/
int main(void) {
	printf("The sum between %d and %d is %d.\n", 10, 20, sum(10, 20));
	return 0;
}

/*
printf is a variadic functions since it can accept a variable number of arguments.

Please notice that before executing it, the sum function is called since we need to resolve all the arguments first.

By looking at the assembly code generated by the compiler, we can define a variable as follows:
A variable 'a' is an identifier for a storage location, which is determined by the compiler to be either a register (for optimization) or a location on the stack/memory.

It is also crucial to understand the lifespan of a variable. Variables declared inside a function are local variables. They "die" when the function returns.
In this code the function sum uses three variables: a, b, c. Those variables cannot be seen by the 'main' function since when the control returns to it, they are no more.
*/
/*
It is a good practice to compile with the warnings active, in order to know if there is some 'smelly' code that can brings to undefined behaviours. For example if we do not match the number of %d with the number of arguments we have an undifined behaviour since if there are fewer arguments, printf prints something aleatory.
To compile with warnings specifies the options "-Wall". E.g. "gcc -Wall <source_file.c>".
*/
